### ISSUE TITLE
how can trust and some question

### ISSUE THREAD

**Issue by heforfree** [salarcode/ExportTelegramContacts#1]
how can trust this app and make sure its safe?
can we delete app later (i mean step2)?
why its not work with two step authorization account?
exported contact can be imported to default phone app?

**Comment by salarcode** [comment]
You create the app_id for yourself and it is not shared elsewhere.
Also the code is available for you to check.

> why its not work with two step authorization account?

This app is not designed to work with 2step authorization.

> exported contact can be imported to default phone app?
yes
