### ISSUE TITLE
api_id_invalid

### ISSUE THREAD

**Issue by mrmasoud67** [salarcode/ExportTelegramContacts#10]
after Select authenticate option, API_ID_INVALID shown. please help me.

**Comment by ghost** [comment]
same for me too

**Comment by salarcode** [comment]
Please read How To Use:
https://github.com/salarcode/ExportTelegramContacts#how-to-use

**Comment by georgehazan** [comment]
@salarcode even after all of that I still receive that error when I try to authenticate
what am I doing wrong?

**Comment by salarcode** [comment]
please make sure the `App_Id` is entered correctly in the `.config` files and there is no space around it
