### ISSUE TITLE
It doesn't export contacts without phone numbers.

### ISSUE THREAD

**Issue by b-codex** [salarcode/ExportTelegramContacts#16]
It works fine with contacts with phone numbers, but regarding to the contacts without phone numbers it doesn't work.

**Comment by minanagehsalalma** [comment]
@b-codex same bro ... have you figured it out ?

**Comment by salarcode** [comment]
In the step "Export contacts without phone? [y/n]" select "Y"

**Comment by minanagehsalalma** [comment]
> In the step "Export contacts without phone? [y/n]" select "n"

@salarcode well, what did that solve?  We want to export these contacts that have telegram id only!

**Comment by salarcode** [comment]
In step "Export contacts without phone? " if you select Y then contact without phone number will also be exported

**Comment by minanagehsalalma** [comment]
> In step "Export contacts without phone? " if you select Y then contact without phone number will also be exported

@salarcode no it doesn't it just gives an empty contact with name only.

**Comment by salarcode** [comment]
That's what the contact is! it doesn't have phone number

**Comment by minanagehsalalma** [comment]
> That's what the contact is! it doesn't have phone number

@salarcode  but it should have what's called a telegram ID!! Which makes it useful has a F use ! What the heck i am gonna do with a contact that has name only ?

**Comment by salarcode** [comment]
Telegram ID is not part of the standard contact, this app exports standard VCard format.

**Comment by minanagehsalalma** [comment]
> Telegram ID is not part of the standard contact, this app exports standard VCard format.

Then it's missing what matters.

**Comment by salarcode** [comment]
TelegramID is not a standard property of contacts, that's limitation of not just Telegram but any other app as well.

**Comment by minanagehsalalma** [comment]
> TelegramID is not a standard property of contacts, that's limitation of not just Telegram but any other app as well.

Dang.. then how can i export/share the contacts  with telegram ids only to my other account?
