### ISSUE TITLE
how to open "ExportTelegramContacts.exe.config" file

### ISSUE THREAD

**Issue by ghost** [salarcode/ExportTelegramContacts#17]
Hello.
I do not have a software to open the "app.config" file and also I do not know the GitHub. please help me and send your reply to my email address. I need to export my telegram contacts but I can not run the "app.config" file. Thanks.

my email address is ......

**Comment by salarcode** [comment]
Use Notepad application in windows
![image](https://user-images.githubusercontent.com/1272095/97061504-d37e6400-15e2-11eb-9bc7-4f48149855d8.png)
