### ISSUE TITLE
UPDATE_APP_TO_LOGIN

### ISSUE THREAD

**Issue by wizzy123** [salarcode/ExportTelegramContacts#23]
UPDATE_APP_TO_LOGIN
You are not authenticated, please authenticate first.

error what to do?

**Comment by salarcode** [comment]
Please read the how to use
https://github.com/salarcode/ExportTelegramContacts#how-to-use

**Comment by wizzy123** [comment]
I did everything according to the instructions but the error still remains

**Comment by wizzy123** [comment]
everything works with the second account, but it doesn't work with this account
