### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by aladaghlou** [salarcode/ExportTelegramContacts#4]
I get this error when connecting to server.
I use a proxy for filtering.
Please see this picture:
[https://imgur.com/a/2ZUIxrU](https://imgur.com/a/2ZUIxrU)

**Comment by salarcode** [comment]
Because Telegram is blocked in Iran.
Only VPN may help, not regular proxy.

**Comment by magpier84** [comment]
ERROR: Can't connect to server:

***************************
Welcome to Telegram Contacts Exporter Version 1.3.0.0
***************************
Connecting to Telegram servers...
Требуемый адрес для своего контекста неверен
