### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by adwaitbhope** [salarcode/ExportTelegramContacts#5]
Gives out an error when a mobile number with a different country code than US is used.

![issue](https://user-images.githubusercontent.com/32306983/41496714-50c458dc-7164-11e8-9d56-e0964f0be14a.jpg)

**Comment by Shree3245** [comment]
Hello, I am actually stuck at the step previous to yours. How did you manage to start the program

**Comment by adwaitbhope** [comment]
Follow the README. First you need to register your application. Then you'll get a unique api_id and api_hash. You need to enter these two values in the app.config file.

**Comment by Shree3245** [comment]
no i already registered and put the id and hash into the code. what i mean is how do i run the program. is there an executible or which file am i supposed to run

**Comment by CptPlayer** [comment]
Hi, how do you run the programme, I already pasted my Api_id and api_hash .-

**Comment by Alecckie** [comment]
**ExportTelegramContacts.exe** is the executable file that you run after pasting the Api_id and Api_hash in the
**ExportTelegramContacts.exe.config** 
Press 1 to authenticate
Press 2 to export contacts
Type n not to export contacts without numbers
**ExportedContacts** folder is the folder where the applications saves the exported contacts
![capture](https://user-images.githubusercontent.com/10174852/51085122-c2ce6800-1745-11e9-81fe-62c21faa70d4.PNG)

**Comment by SilverKylin** [comment]
> 
> 
> Gives out an error when a mobile number with a different country code than US is used.
> 
> ![issue](https://user-images.githubusercontent.com/32306983/41496714-50c458dc-7164-11e8-9d56-e0964f0be14a.jpg)

I have the same issue. Any solution from the developer?

**Comment by Alecckie** [comment]
@SilverKylin I'm from Kenya with country code 254 and this worked for me. I think it fails for some selected country codes outside US but not all.

**Comment by salarcode** [comment]
If you don't receive authentication code it is your provider that blocks or has issues, not this application

**Comment by SilverKylin** [comment]
> If you don't receive authentication code it is your provider that blocks or has issues, not this application

The app shows that I cannot use my number for authentication, not that authentication code cannot be received. The issue is definitely at your app side, nothing to do with the provider. The request for authentication code wasn't even sent out to my provider because of the error.

**Comment by salarcode** [comment]
@SilverKylin the has no logic to validate, control or process the phone number.
*Everything* is sent to telegram servers.
If anything prevents this communication with servers, it is on users.

**Comment by salarcode** [comment]
Try 1.4 servers are updated
