### ISSUE TITLE
Unable to authenticate using phone number

### ISSUE THREAD

**Issue by SilverKylin** [salarcode/ExportTelegramContacts#6]
![TelegramExporter](https://user-images.githubusercontent.com/51535609/59161278-3917a080-8b13-11e9-8465-39e284b6d9ae.png)

Cannot authenticate using my valid telegram phone number

**Comment by salarcode** [comment]
Application updated, try again

**Comment by ghost** [comment]
Was looking for a solution for this as v1.2 did not support this.

Nevertheless, according to your new update, the new updated application could not work at all. 

> 'Requested address not valid in this context'
