### ISSUE TITLE
Was looking for a solution for this as v1.2 did not support this.

### ISSUE THREAD

**Issue by ghost** [salarcode/ExportTelegramContacts#7]
Was looking for a solution for this as v1.2 did not support this.

Nevertheless, according to your new update, the new updated application could not work at all. 

> 'Requested address not valid in this context'

_Originally posted by @Oraclesports in https://github.com/salarcode/ExportTelegramContacts/issues/6#issuecomment-511404001_

**Comment by salarcode** [comment]
Try 1.4 servers updated
